#![warn(missing_docs, rustdoc::broken_intra_doc_links)]
//! Node.js binding surface for the Naos compiler.

use napi_derive::napi;

const DIAGNOSTIC_REASON_PREFIX: &str = "NAOS_COMPILER_DIAGNOSTICS:";

fn to_napi_error(error: &naos_core::CompilerError, filename: &str, source: &str) -> napi::Error {
    let payload = serde_json::json!({
        "message": error.to_string(),
        "diagnostics": error.diagnostics_with_source(filename, Some(source)),
    });
    napi::Error::from_reason(format!("{DIAGNOSTIC_REASON_PREFIX}{payload}"))
}

/// Version metadata for the loaded native compiler.
#[napi(object)]
pub struct NativeInfo {
    /// Current Rust compiler core package version.
    pub core_version: String,
}

/// Returns metadata for the native compiler.
#[napi]
#[must_use]
pub fn get_native_info() -> NativeInfo {
    NativeInfo {
        core_version: naos_core::core_version().to_string(),
    }
}

/// Request passed to the native component transform workflow.
#[napi(object)]
pub struct NativeTransformRequest {
    /// Original TypeScript/TSX source.
    pub source: String,
    /// Filename used for parser source-type detection and diagnostics.
    pub filename: String,
    /// Package name read from the owning package file.
    pub package_name: String,
    /// Optional package version read from the owning package file.
    pub package_version: Option<String>,
    /// Validated Custom Element prefix for the owning package.
    pub tag_prefix: String,
    /// DOM construction backend: `auto`, `imperative`, or `template`.
    pub dom_backend: Option<String>,
}

/// Source map returned by the native compiler transform.
#[napi(object)]
pub struct NativeSourceMap {
    /// Source map version.
    pub version: u32,
    /// Generated output filename.
    pub file: String,
    /// Original source filenames.
    pub sources: Vec<String>,
    /// Original source text.
    pub sources_content: Vec<String>,
    /// Symbol names referenced by mappings.
    pub names: Vec<String>,
    /// Source map v3 VLQ mappings.
    pub mappings: String,
}

/// `?inline` style import captured by the compiler.
#[napi(object)]
pub struct NativeStyleImport {
    /// Local binding name used in the component options.
    pub local_name: String,
    /// Import source specifier, including the `?inline` query.
    pub source: String,
}

/// Public prop declaration captured by the compiler.
#[napi(object)]
pub struct NativePropDefinition {
    /// Public prop (property) name.
    pub prop_name: String,
    /// Observed HTML attribute name for reflected kinds.
    pub attribute_name: String,
    /// Prop conversion kind: `string`, `boolean`, `number`, or `rich`.
    pub kind: String,
    /// Source text of the default value expression.
    pub default_value: String,
}

/// Typed event declaration captured by the compiler.
#[napi(object)]
pub struct NativeEventDefinition {
    /// Custom event name dispatched by the component.
    pub event_name: String,
    /// TypeScript detail type source, when provided.
    pub detail_type: Option<String>,
}

/// Result returned by the native component transform workflow.
#[napi(object)]
pub struct NativeTransformResult {
    /// Generated JavaScript module source.
    pub code: String,
    /// Source map generated by the Rust compiler.
    pub map: Option<NativeSourceMap>,
    /// Whether the generated code differs from the input module source.
    pub has_changed: bool,
    /// `?inline` style imports the compiler saw in the module.
    pub style_imports: Vec<NativeStyleImport>,
    /// Custom Element tag name derived from package and component names.
    pub tag_name: String,
    /// Generated JavaScript class name.
    pub class_name: String,
    /// Public authoring export name for function components.
    pub export_name: Option<String>,
    /// Whether the component renders into a shadow root.
    pub shadow: bool,
    /// Public prop declarations for typed-element emission.
    pub props: Vec<NativePropDefinition>,
    /// Typed event declarations for typed-element emission.
    pub events: Vec<NativeEventDefinition>,
    /// Package name that owns this component.
    pub package_name: String,
    /// Optional version of the package that owns this component.
    pub package_version: Option<String>,
    /// Custom Element prefix resolved for the package.
    pub tag_prefix: String,
}

fn native_prop_kind(kind: naos_core::PropKind) -> String {
    match kind {
        naos_core::PropKind::String => "string".to_owned(),
        naos_core::PropKind::Boolean => "boolean".to_owned(),
        naos_core::PropKind::Number => "number".to_owned(),
        naos_core::PropKind::Rich => "rich".to_owned(),
    }
}

impl From<naos_core::SourceMap> for NativeSourceMap {
    fn from(source_map: naos_core::SourceMap) -> Self {
        Self {
            file: source_map.file,
            mappings: source_map.mappings,
            names: source_map.names,
            sources: source_map.sources,
            sources_content: source_map.sources_content,
            version: u32::from(source_map.version),
        }
    }
}

/// Request passed to the native Declarative Shadow DOM prerender workflow.
#[napi(object)]
pub struct NativeDeclarativeShadowDomRequest {
    /// Original TypeScript/TSX source.
    pub source: String,
    /// Filename used for parser source-type detection and diagnostics.
    pub filename: String,
    /// Package name read from the owning package file.
    pub package_name: String,
    /// Optional package version read from the owning package file.
    pub package_version: Option<String>,
    /// Validated Custom Element prefix for the owning package.
    pub tag_prefix: String,
    /// Optional JSON object containing initial prop values.
    pub props_json: Option<String>,
    /// Optional JSON object containing resolved `?inline` CSS text by local import name.
    pub inline_styles_json: Option<String>,
}

/// Result returned by the native Declarative Shadow DOM prerender workflow.
#[napi(object)]
pub struct NativeDeclarativeShadowDomResult {
    /// Package-stable Custom Element tag name, for example `acme-counter`.
    pub tag_name: String,
    /// Generated JavaScript class name.
    pub class_name: String,
    /// Public authoring export name for function components.
    pub export_name: Option<String>,
    /// Full custom element host HTML.
    pub html: String,
    /// Serialized `<template shadowrootmode="open">` fragment.
    pub template_html: String,
    /// Whether the component renders into a shadow root.
    pub shadow: bool,
    /// Whether the result includes Declarative Shadow DOM.
    pub uses_declarative_shadow_dom: bool,
    /// Package name that owns this component.
    pub package_name: String,
    /// Optional version of the package that owns this component.
    pub package_version: Option<String>,
    /// Custom Element prefix resolved for the package.
    pub tag_prefix: String,
}

/// Transforms an Naos component module into native Custom Element source.
///
/// # Errors
///
/// Returns a Node error when parsing, analysis, or code generation fails.
#[napi]
#[allow(clippy::needless_pass_by_value)]
pub fn transform_component(request: NativeTransformRequest) -> napi::Result<NativeTransformResult> {
    let dom_backend = naos_core::DomBackend::parse(request.dom_backend.as_deref())
        .map_err(|error| to_napi_error(&error, &request.filename, &request.source))?;
    let package = naos_core::PackageContext {
        name: request.package_name,
        version: request.package_version,
        tag_prefix: request.tag_prefix,
    };
    naos_core::transform_component_module_with_dom_backend(
        &request.source,
        &request.filename,
        &package,
        dom_backend,
    )
    .map(|result| NativeTransformResult {
        code: result.code,
        map: result.map.map(Into::into),
        has_changed: result.has_changed,
        style_imports: result
            .style_imports
            .into_iter()
            .map(|style_import| NativeStyleImport {
                local_name: style_import.local_name,
                source: style_import.source,
            })
            .collect(),
        tag_name: result.tag_name,
        class_name: result.class_name,
        export_name: result.export_name,
        shadow: result.shadow,
        props: result
            .props
            .into_iter()
            .map(|prop| NativePropDefinition {
                prop_name: prop.prop_name,
                attribute_name: prop.attribute_name,
                kind: native_prop_kind(prop.kind),
                default_value: prop.default_value,
            })
            .collect(),
        events: result
            .events
            .into_iter()
            .map(|event| NativeEventDefinition {
                event_name: event.event_name,
                detail_type: event.detail_type,
            })
            .collect(),
        package_name: result.package.name,
        package_version: result.package.version,
        tag_prefix: result.package.tag_prefix,
    })
    .map_err(|error| to_napi_error(&error, &request.filename, &request.source))
}

/// Prerenders an Naos component module as Declarative Shadow DOM host HTML.
///
/// # Errors
///
/// Returns a Node error when parsing, analysis, or serialization fails.
#[napi]
#[allow(clippy::needless_pass_by_value)]
pub fn render_declarative_shadow_dom(
    request: NativeDeclarativeShadowDomRequest,
) -> napi::Result<NativeDeclarativeShadowDomResult> {
    let package = naos_core::PackageContext {
        name: request.package_name,
        version: request.package_version,
        tag_prefix: request.tag_prefix,
    };
    naos_core::render_declarative_shadow_dom_module_with_inline_styles(
        &request.source,
        &request.filename,
        &package,
        request.props_json.as_deref(),
        request.inline_styles_json.as_deref(),
    )
    .map(|result| NativeDeclarativeShadowDomResult {
        tag_name: result.tag_name,
        class_name: result.class_name,
        export_name: result.export_name,
        html: result.html,
        template_html: result.template_html,
        shadow: result.shadow,
        uses_declarative_shadow_dom: result.uses_declarative_shadow_dom,
        package_name: result.package.name,
        package_version: result.package.version,
        tag_prefix: result.package.tag_prefix,
    })
    .map_err(|error| to_napi_error(&error, &request.filename, &request.source))
}
