// AUTO-GENERATED by Ardo - Do not edit manually

import { type RouteConfig, route, index } from "@react-router/dev/routes"

export default [
  index("routes/home.tsx"),
  route("guide/authoring", "routes/guide/authoring.mdx"),
  route("guide/demos", "routes/guide/demos.mdx"),
  route("guide/getting-started", "routes/guide/getting-started.mdx"),
  route("guide/styling-and-dsd", "routes/guide/styling-and-dsd.mdx"),
  route("guide/testing", "routes/guide/testing.mdx"),
  route("playground", "routes/playground.tsx"),
  route("reference/api", "routes/reference/api.mdx"),
  route("reference/packages", "routes/reference/packages.mdx"),
] satisfies RouteConfig
